name: ci
on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      git-ref:
        description: Manual trigger if the tags trigger does not start
        required: false
env:
  DOCKER_REPO: wde-whos
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set Tag
        run: |
          echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV
      - name: Test Tag
        run: |
          echo $TAG
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker_files
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}-cache:latest,mode=max

      - name: build and push latest tag
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.DOCKER_REPO }}:${{ env.TAG_LATEST }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}-cache:latest,mode=max
